apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto.conf: |
  log_dest stdout
  log_type all
  log_timestamp true
  listener 9001

  #you can seperate by the --- triple line
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto.conf: |
  log_dest stdout
  log_type all
  log_timestamp true
  listener 9001