apiVersion: v1
kind: Service
metadata:
  name: {.values.service.name}
spec:
  selector:
    app: {{.values.service.app}}
  ports:
    -protocol: TCP
     port: {{ .values.service.port}}
     targetPort: {{.values.service.targetport}}